export const superAdminList = [
  "bryce.mercines@whitecloak.com",
  "vince.carandang@whitecloak.com",
  "rafael.tiongson@whitecloak.com",
  "donn.gamboa@whitecloak.com",
  "anne.liango@whitecloak.com",
  "miguel.fermin@whitecloak.com",
  "michelle.cruz@whitecloak.com",
  "anne.liangco@whitecloak.com",
  "lyra.cunado@whitecloak.com",
  "aezel.labaco@whitecloak.com",
  "maricar.belarmino@whitecloak.com",
  "thea.juego@whitecloak.com",
  "sandra.carlos@whitecloak.com",
  "darylle.villanueva@whitecloak.com",
  "linda.agmata@whitecloak.com",
];
